# Generated by Django 3.0.5 on 2020-04-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ConfManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('board',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfManager.Board')),
            ],
        ),
        migrations.CreateModel(
            name='PowerController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='NetPort',
            new_name='NetInterface',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('to_be_released', models.DateTimeField(null=True)),
                ('configuration',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfManager.Configuration',
                                   unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('port_number', models.IntegerField()),
                ('controller',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfManager.PowerController')),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='ConfManager.PowerSupply'),
        ),
    ]
