# Generated by Django 3.2.9 on 2021-12-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0002_auto_20211204_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
