# Generated by Django 3.0.5 on 2020-04-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ConfManager', '0002_auto_20200425_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='configuration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ConfManager.Configuration'),
        ),
    ]
