# Generated by Django 3.0.5 on 2020-05-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0004_auto_20200425_1940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetInterface',
        ),
    ]
