# Generated by Django 3.1.3 on 2021-03-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0007_auto_20210327_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powersupply',
            options={'verbose_name_plural': 'Power supplies'},
        ),
        migrations.RemoveField(
            model_name='powersupply',
            name='name',
        ),
        migrations.AlterField(
            model_name='rackslot',
            name='board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ConfManager.board'),
        ),
    ]
