# Generated by Django 3.1.3 on 2021-03-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0008_auto_20210327_1001'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='powersupply',
            constraint=models.UniqueConstraint(fields=('port_number', 'controller'), name='unique_port_controller'),
        ),
    ]
