# Generated by Django 3.1.3 on 2021-03-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0009_auto_20210327_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powersupply',
            options={'ordering': ['port_number'], 'verbose_name_plural': 'Power supplies'},
        ),
    ]
