# Generated by Django 3.1.7 on 2021-04-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ConfManager', '0009_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='interfaces',
            field=models.ManyToManyField(to='ConfManager.Interface'),
        ),
    ]
