# Generated by Django 3.1.3 on 2021-03-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0010_auto_20210327_1126'),
        ('ConfManager', '0003_label'),
    ]

    operations = [
    ]
