# Generated by Django 3.1.7 on 2021-04-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0011_networkinterface_uartinterface'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackplaneNetworkInterface',
            fields=[
                ('interface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ConfManager.interface')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ConfManager.interface',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfManager.board')),
            ],
        ),
    ]
