# Generated by Django 3.1.7 on 2021-04-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ConfManager', '0012_backplanenetworkinterface_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('name', 'board_id'), name='unique_target_device'),
        ),
    ]
