# Generated by Django 3.2.5 on 2021-07-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0018_boardinterface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='interfaces',
        ),
    ]
