# Generated by Django 3.2.5 on 2021-07-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0020_delete_boardinterface'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTypeDeviceAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='boardtypedevice',
            name='aliases',
            field=models.ManyToManyField(to='ConfManager.BoardTypeDeviceAlias'),
        ),
    ]
