# Generated by Django 3.2.5 on 2021-09-15 20:49

import ConfManager.models.reservation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ConfManager', '0022_alter_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='to_be_released',
        ),
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='release_date',
            field=models.DateTimeField(default=ConfManager.models.reservation.next_year),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conf_reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
