# Generated by Django 3.2.5 on 2021-09-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0023_auto_20210915_2049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuration',
            new_name='TestPlatform',
        ),
    ]
