# Generated by Django 3.2.5 on 2021-09-30 19:39

from django.db import migrations, models
import django.db.models.deletion

from ConfManager.models.device import DeviceType


def _make_default():
    return DeviceType.objects.get_or_create(name='ToBeDefined')[0].id


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0025_devicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(default=_make_default, on_delete=django.db.models.deletion.CASCADE, to='ConfManager.devicetype'),
            preserve_default=False,
        ),
    ]
