# Generated by Django 3.2.5 on 2021-10-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0027_auto_20210930_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduledefinition',
            name='board',
        ),
        migrations.DeleteModel(
            name='BoardDefinition',
        ),
        migrations.DeleteModel(
            name='ModuleDefinition',
        ),
    ]
