# Generated by Django 3.2.5 on 2021-10-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0028_auto_20211002_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardtypedevicealias',
            options={'verbose_name_plural': 'Board type device aliases'},
        ),
    ]
