# Generated by Django 3.2.5 on 2021-10-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0029_alter_boardtypedevicealias_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Unit',
        ),
        migrations.RenameModel(
            old_name='BoardType',
            new_name='UnitType',
        ),
    ]
