# Generated by Django 3.2.5 on 2021-10-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0030_auto_20211002_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittype',
            name='devices',
        ),
        migrations.DeleteModel(
            name='BoardTypeDevice',
        ),
    ]
