# Generated by Django 3.2.5 on 2021-10-02 19:31

from django.db import migrations, models
import django.db.models.deletion
from polymorphic.utils import reset_polymorphic_ctype


def _reset_polymorphic_unit_ctype(apps, schema_editor):
    unit_type_model = apps.get_model('ConfManager', 'UnitType')
    board_type_model = apps.get_model('ConfManager', 'BoardType')
    module_type_model = apps.get_model('ConfManager', 'ModuleType')
    reset_polymorphic_ctype(unit_type_model, board_type_model, module_type_model)
    reset_polymorphic_ctype(unit_type_model, board_type_model, module_type_model, ignore_existing=True)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ConfManager', '0031_auto_20211002_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('unittype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ConfManager.unittype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ConfManager.unittype',),
        ),
        migrations.AlterModelOptions(
            name='unittype',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='unittype',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_confmanager.unittype_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('unittype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ConfManager.unittype')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ConfManager.boardtype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ConfManager.unittype',),
        ),
        migrations.RunPython(_reset_polymorphic_unit_ctype, migrations.RunPython.noop),
    ]
