# Generated by Django 3.2.5 on 2021-10-03 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0032_auto_20211002_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardtypedevicealias',
            name='board_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ConfManager.boardtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardtypedevicealias',
            name='device_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ConfManager.devicetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardtypedevicealias',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='boardtypedevicealias',
            constraint=models.UniqueConstraint(fields=('board_type_id', 'name'), name='unique_board_type_device'),
        ),
    ]
