# Generated by Django 3.2.5 on 2021-10-03 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0033_auto_20211003_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackplaneGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='testplatform',
            name='power',
        ),
        migrations.CreateModel(
            name='BackplaneSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfManager.backplanegroup')),
                ('power', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfManager.powersupply')),
            ],
        ),
        migrations.AddField(
            model_name='testplatform',
            name='backplane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfManager.backplaneslot'),
        ),
        migrations.AddConstraint(
            model_name='backplaneslot',
            constraint=models.UniqueConstraint(fields=('group_id', 'slot_number'), name='unique_backplane_group_slot'),
        ),
    ]
