# Generated by Django 3.2.5 on 2021-10-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0034_auto_20211003_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='configuration',
            new_name='platform',
        ),
    ]
