# Generated by Django 3.2.5 on 2021-10-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0035_rename_configuration_reservation_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rackslot',
            name='board',
        ),
        migrations.RemoveField(
            model_name='rackslot',
            name='rack',
        ),
        migrations.DeleteModel(
            name='Rack',
        ),
        migrations.DeleteModel(
            name='RackSlot',
        ),
    ]
