# Generated by Django 3.2.5 on 2021-10-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0037_auto_20211009_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplatform',
            name='backplane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfManager.backplaneslot'),
        ),
        migrations.AlterField(
            model_name='testplatform',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfManager.unit'),
        ),
        migrations.AlterField(
            model_name='testplatform',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
