# Generated by Django 3.2.5 on 2021-10-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0038_auto_20211009_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardtypedevicealias',
            name='board_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_alias_set', to='ConfManager.boardtype'),
        ),
    ]
