# Generated by Django 3.2.5 on 2021-10-10 20:34

from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0040_add_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('mac', macaddress.fields.MACAddressField(integer=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfManager.network')),
            ],
            options={
                'verbose_name_plural': 'Network addresses',
            },
        ),
        migrations.AddConstraint(
            model_name='networkaddress',
            constraint=models.UniqueConstraint(fields=('network', 'ip', 'mac'), name='unique_network_address'),
        ),
    ]
