# Generated by Django 3.2.5 on 2021-10-11 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0041_auto_20211010_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplatform',
            name='backplane',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfManager.backplaneslot'),
        ),
        migrations.AlterField(
            model_name='testplatform',
            name='board',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfManager.unit'),
        ),
    ]
