# Generated by Django 3.2.5 on 2021-10-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0042_auto_20211011_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='device_number',
            field=models.IntegerField(default=0),
        ),
    ]
