# Generated by Django 3.2.5 on 2021-10-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0043_devicetype_device_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkinterface',
            name='address',
        ),
    ]
