# Generated by Django 3.2.5 on 2021-10-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0045_networkinterface_network_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='interfaces',
        ),
        migrations.AddField(
            model_name='interface',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ConfManager.device'),
            preserve_default=False,
        ),
    ]
