# Generated by Django 3.2.5 on 2021-10-20 20:02

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0046_auto_20211017_1850'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='networkaddress',
            name='unique_network_address',
        ),
        migrations.AlterField(
            model_name='networkaddress',
            name='mac',
            field=macaddress.fields.MACAddressField(blank=True, default=None, integer=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='networkaddress',
            constraint=models.UniqueConstraint(fields=('network', 'ip'), name='unique_network_address'),
        ),
    ]
