# Generated by Django 3.2.5 on 2021-10-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0047_auto_20211020_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInterfaceBase',
            fields=[
                ('interface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ConfManager.interface')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ConfManager.interface',),
        ),
        migrations.RemoveField(
            model_name='networkinterface',
            name='network_address',
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='network',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfManager.network'),
        ),
    ]
