# Generated by Django 3.2.5 on 2021-10-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0048_auto_20211020_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkInterfaceBase',
        ),
    ]
