# Generated by Django 3.2.5 on 2021-10-21 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0049_delete_networkinterfacebase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkinterface',
            name='network',
        ),
        migrations.AddField(
            model_name='networkaddress',
            name='interface',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_address', to='ConfManager.interface'),
        ),
    ]
