# Generated by Django 3.2.5 on 2021-10-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0050_auto_20211021_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backplanenetworkinterface',
            name='interface_ptr',
        ),
        migrations.RemoveField(
            model_name='networkaddress',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='networkaddress',
            name='mac',
        ),
        migrations.RemoveField(
            model_name='networkinterface',
            name='interface_ptr',
        ),
        migrations.AddField(
            model_name='backplanenetworkinterface',
            name='backplane',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='ConfManager.backplaneslot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backplanenetworkinterface',
            name='device_number',
            field=models.IntegerField(default=789),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BaseNetworkInterface',
            fields=[
                ('interface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ConfManager.interface')),
                ('network_address', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfManager.networkaddress')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ConfManager.interface',),
        ),
        migrations.AddField(
            model_name='backplanenetworkinterface',
            name='basenetworkinterface_ptr',
            field=models.OneToOneField(auto_created=True, default=456, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ConfManager.basenetworkinterface'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='basenetworkinterface_ptr',
            field=models.OneToOneField(auto_created=True, default=897, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ConfManager.basenetworkinterface'),
            preserve_default=False,
        ),
    ]
