# Generated by Django 3.0.5 on 2020-05-03 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('mac_address', models.CharField(max_length=17, null=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IpReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.DateTimeField(null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('interface_ref',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='IPLabo.NetInterface')),
                ('ip_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='IPLabo.IpPool')),
            ],
        ),
    ]
