# Generated by Django 3.1.3 on 2020-11-08 19:21

from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('IPLabo', '0002_auto_20200503_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippool',
            name='arp_mac',
            field=macaddress.fields.MACAddressField(integer=True, null=True),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ippool',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='mac_address',
            field=macaddress.fields.MACAddressField(integer=True, null=True),
        ),
        migrations.CreateModel(
            name='Arp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', macaddress.fields.MACAddressField(integer=True, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='IPLabo.ippool')),
            ],
        ),
    ]
