# Generated by Django 3.1.3 on 2020-12-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPLabo', '0005_auto_20201211_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='ippool',
            name='labels',
            field=models.ManyToManyField(to='IPLabo.Label'),
        ),
    ]
