# Generated by Django 4.1.1 on 2022-09-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0006_add_uart_stuff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uartport',
            old_name='server',
            new_name='controller',
        ),
        migrations.RenameField(
            model_name='uartport',
            old_name='index',
            new_name='port_number',
        ),
    ]
