# Generated by Django 4.1.1 on 2022-09-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0007_rename_server_uartport_controller_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uartport',
            options={'ordering': ['controller__name', 'port_number']},
        ),
        migrations.AlterField(
            model_name='uartport',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='ConfManager.uartserver'),
        ),
        migrations.AlterField(
            model_name='uartport',
            name='port_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='uartport',
            constraint=models.UniqueConstraint(fields=('port_number', 'controller'), name='uartport_unique_port_controller'),
        ),
    ]
