# Generated by Django 4.1.1 on 2022-09-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0008_uartport_use_multi_port_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powersupply',
            options={'verbose_name_plural': 'Power supplies'},
        ),
        migrations.RemoveConstraint(
            model_name='powersupply',
            name='unique_port_controller',
        ),
        migrations.AddField(
            model_name='powercontroller',
            name='url',
            field=models.CharField(default='To be defined', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='ConfManager.powercontroller'),
        ),
        migrations.AlterField(
            model_name='uartserver',
            name='url',
            field=models.CharField(max_length=30),
        ),
    ]
