# Generated by Django 4.1.1 on 2022-09-25 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0009_powersupply_use_multi_port_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backplaneslot',
            options={'ordering': ['group__name', 'slot_number']},
        ),
        migrations.AlterField(
            model_name='backplanegroup',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='backplaneslot',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='ConfManager.backplanegroup'),
        ),
        migrations.AlterField(
            model_name='backplaneslot',
            name='power',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfManager.powersupply'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='port_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
