# Generated by Django 4.1.1 on 2022-09-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0010_alter_backplaneslot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backplaneslot',
            options={'ordering': ['group__name', 'port_number']},
        ),
        migrations.RemoveConstraint(
            model_name='backplaneslot',
            name='unique_backplane_group_slot',
        ),
        migrations.RenameField(
            model_name='backplaneslot',
            old_name='slot_number',
            new_name='port_number',
        ),
        migrations.AddConstraint(
            model_name='backplaneslot',
            constraint=models.UniqueConstraint(fields=('group_id', 'port_number'), name='unique_backplane_group_port'),
        ),
    ]
