# Generated by Django 4.1.1 on 2022-09-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0011_alter_backplaneslot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backplaneslot',
            options={'ordering': ['controller__name', 'port_number']},
        ),
        migrations.RemoveConstraint(
            model_name='backplaneslot',
            name='unique_backplane_group_port',
        ),
        migrations.RenameField(
            model_name='backplaneslot',
            old_name='group',
            new_name='controller',
        ),
        migrations.AddConstraint(
            model_name='backplaneslot',
            constraint=models.UniqueConstraint(fields=('controller', 'port_number'), name='unique_backplane_group_port'),
        ),
    ]
