# Generated by Django 4.1 on 2022-10-13 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfManager', '0012_alter_backplaneslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplatform',
            name='uart_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfManager.uartgroup'),
        ),
    ]
