# Generated by Django 3.2.9 on 2021-12-04 16:20

import LabNet.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', LabNet.models.IntegerIPAddressField(unique=True)),
                ('mac_address', macaddress.fields.MACAddressField(blank=True, default=None, integer=True, null=True)),
                ('labels', models.ManyToManyField(to='LabNet.Label')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabNet.network')),
            ],
            options={
                'verbose_name_plural': 'Network addresses',
                'ordering': ['network', 'ip'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('release', models.DateField(default=LabNet.models.next_year)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LabNet.networkaddress')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Arp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', macaddress.fields.MACAddressField(integer=True, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabNet.networkaddress')),
            ],
        ),
        migrations.AddConstraint(
            model_name='networkaddress',
            constraint=models.UniqueConstraint(fields=('network', 'ip'), name='ln_unique_network_address'),
        ),
        migrations.AddConstraint(
            model_name='networkaddress',
            constraint=models.UniqueConstraint(fields=('network', 'mac_address'), name='ln_unique_network_mac_address'),
        ),
    ]
