# Generated by Django 3.1.3 on 2020-12-11 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('LabNet', '0004_remove_ippool_arp_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arp',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabNet.ippool'),
        ),
    ]
