# Generated by Django 3.1.7 on 2021-03-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('LabNet', '0006_auto_20201211_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ippool',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
