# Generated by Django 3.2.5 on 2021-07-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabNet', '0007_auto_20210328_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipreservation',
            old_name='interface_ref',
            new_name='interface',
        ),
        migrations.RenameField(
            model_name='ipreservation',
            old_name='ip_ref',
            new_name='ip',
        ),
    ]
