# Generated by Django 3.2.5 on 2021-07-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabNet', '0008_fixup_ipreservation_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipreservation',
            name='id',
        ),
        migrations.AlterField(
            model_name='ipreservation',
            name='ip',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='LabNet.ippool'
            ),
        ),
    ]
