# Generated by Django 3.2.5 on 2021-07-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabNet', '0009_ipreservation_ip_primary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IpPool',
            new_name='Ip',
        ),
    ]
