# Generated by Django 3.2.5 on 2021-07-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabNet', '0010_rename_ippool_ip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IpReservation',
            new_name='Reservation',
        ),
    ]
