# Generated by Django 3.2.5 on 2021-07-20 17:03

import LabNet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabNet', '0011_rename_ipreservation_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='release',
            field=models.DateTimeField(default=LabNet.models.next_year),
        ),
    ]
