# Generated by Django 3.2.5 on 2021-07-21 21:20
import ipaddress

import LabNet.models
from django.db import migrations, models


def gen_ip_num(apps, _schema_editor):
    ip = apps.get_model('LabNet', 'Ip')
    for row in ip.objects.all():
        row.ip_num = ipaddress.ip_address(row.ip)
        row.save(update_fields=['ip_num'])


def gen_ip(apps, _schema_editor):
    ip = apps.get_model('LabNet', 'Ip')
    for row in ip.objects.all():
        row.ip = str(ipaddress.ip_address(row.ip_num))
        row.save(update_fields=['ip'])


class Migration(migrations.Migration):

    dependencies = [
        ('LabNet', '0012_reservations_dates_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='ip_num',
            field=LabNet.models.IntegerIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.GenericIPAddressField(unique=False, null=True),
        ),
        migrations.RunPython(gen_ip_num, reverse_code=gen_ip),
        migrations.AlterField(
            model_name='ip',
            name='ip_num',
            field=LabNet.models.IntegerIPAddressField(unique=True, null=False),
        ),
        migrations.RemoveField(
            model_name='ip',
            name='ip', ),
        migrations.RenameField(
            model_name='ip',
            old_name='ip_num',
            new_name='ip'
        ),
    ]
