# Generated by Django 3.2.5 on 2021-07-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabNet', '0014_ip_comment_moved_to_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='interface',
        ),
        migrations.DeleteModel(
            name='NetInterface',
        ),
    ]
