# Generated by Django 3.2.5 on 2021-07-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabNet', '0015_remove_net_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LabNet.ip'),
        ),
    ]
