# Generated by Django 3.2.5 on 2021-07-29 09:54

import LabNet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabNet', '0017_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='release',
            field=models.DateField(default=LabNet.models.next_year),
        ),
    ]
